repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0
  hooks:
  - id: check-added-large-files
  - id: check-byte-order-marker
  - id: check-docstring-first
  - id: check-json
  - id: check-yaml
  - id: debug-statements
    language_version: python3.6
  - id: detect-private-key
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: fix-encoding-pragma
  - id: flake8
    args:
    - --all-files
  - id: mixed-line-ending
  - id: name-tests-test
    files: ^mysite/tests.+\.py$
  - id: requirements-txt-fixer
  - id: trailing-whitespace
- repo: https://github.com/asottile/add-trailing-comma
  rev: v0.7.1
  hooks:
  - id: add-trailing-comma
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.3.1
  hooks:
  - id: reorder-python-imports
    language_version: python3.6
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.4
  hooks:
  - id: autopep8
    args:
    - --aggressive
    - --all-files
    - --in-place
- repo: https://github.com/asottile/pyupgrade
  rev: v1.8.0
  hooks:
  - id: pyupgrade
    args:
    - --py3-plus
